---
title: "Exercises Week 1"
author: "Econometrics"
output: pdf_document
---

\begin{enumerate}
	\item \textbf{Ex. 2.6 in ETM}: Prove that, if the $k$ columns of $X$ are linearly independent, each vector $z$ in $\mathcal{S}(X)$ can be expressed as $Xb$ for one and only one $k$-vector $b$. Hint: Suppose that there are two different vectors, $b_1$ and $b_2$, such that $z = Xb_i$, $i = 1, 2$, and show that this implies that the columns of $X$ are linearly dependent.
	
	\item \textbf{Ex. 2.9 in ETM}: Prove algebraically that $P_XM_X = O$. Use only the definition that $P_X+M_X=I$, and the idempotency of $P_X$.

  	\item \textbf{Ex. 3.1 in ETM}: Generate a sample of size 25 from the model 
	$$y_t = \beta_1+\beta_2 y_{t-1}+u_t,$$ 
	with $\beta_1= 1$ and $\beta_2 = 0.8$. For simplicity, assume that $y_0 = 0$ and that the $u_t$ are $NID(0, 1)$. Use this sample to compute the OLS estimates $\hat{\beta}_1$ and $\hat{\beta}_2$. Repeat at least 100 times, and find the averages of the $\hat{\beta}_1$ and $\hat{\beta}_2$. Use these averages to estimate the bias of the OLS estimators of $\beta_1$ and $\beta_2$.
	
  Repeat this exercise for sample sizes of 50, 100, and 200. What happens to the bias of $\hat{\beta}_1$ and $\hat{\beta}_2$ as the sample size is increased?
	
	\item \textbf{Section 2.7 in AGME}: Follow the example on the Capital Asset Pricing Model (CAPM) from AGME (PDF attached titled \textit{CAPM\textunderscore example}) and replicate the tables. The data is available on the \textit{Ecdat} library under \textit{Capm}.
	
	
  	\item \textbf{Exercise 2.3 in AGME}: Work on the empirical regression exercise from Asset Pricing in AGME (PDF attached titled \textit{FactorModel\textunderscore AGME}). The data is available on the \textit{assets2.dat} file.
	
	On \textbf{g}, "partial slopes" refer to the individual betas.
	

	
\end{enumerate}